### ISSUE TITLE
Cut new release?

### ISSUE THREAD

**Issue by krusynth** [Grasruts/static#2]
Hi, could you please cut a new release?  I'm having the issue that #1 fixes.  Trying to install from git directly is causing bundler to throw `The validation error was 'capistrano-scm-static-0.0.2 contains itself (capistrano-scm-static-0.0.2.gem), check your files list'` for some reason, so that's not an option.

**Comment by sushant12** [comment]
Bumped the version to `0.0.3`

Thank you for using the gem

**Comment by krusynth** [comment]
Works perfectly, thank you so much!
